workflows:
  ios-capacitor-build:
    name: Scoundrel iOS Build
    environment:
      node: latest

    scripts:
      - npm install
      - npx cap add ios
      - npx cap sync ios

    artifacts:
      - ios/**/*.ipa