workflows:
  ios-capacitor-build:
    name: Scoundrel iOS Build

    environment:
      node: latest
      xcode: latest

    scripts:
      - npm install

      - npx cap add ios || true
      - npx cap sync ios

      - cd ios/App
      - pod install

      - cd ../..
      - npx cap build ios

    artifacts:
      - ios/**/*.ipa